namespace: rpunt
name: cockroachdb
version: 1.0.0
readme: README.md
authors:
  - Ryan Punt @rpunt
description: Ansible collection for managing CockroachDB
license_file: LICENSE
tags:
  - database
  - cockroachdb
  - sql
dependencies: {}
repository: https://github.com/rpunt/ansible_cockroachdb
documentation: https://github.com/rpunt/ansible_cockroachdb/blob/main/README.md
homepage: https://github.com/rpunt/ansible_cockroachdb
issues: https://github.com/rpunt/ansible_cockroachdb/issues
build_ignore:
  - cockroach-data
  - "*.tar.gz"
  - ansible_collections
  - container_setup.sh
