---
# Example playbook for managing CockroachDB partitioned tables
- name: Manage CockroachDB partitioned tables
  hosts: cockroachdb_servers
  gather_facts: false
  vars:
    cockroach_ssl_cert: "/path/to/client.crt"
    cockroach_ssl_key: "/path/to/client.key"
    cockroach_ssl_rootcert: "/path/to/ca.crt"
    cockroach_host: "localhost"
    cockroach_port: 26257
    cockroach_user: "root"

  tasks:
    - name: Create geographic_sales database
      cockroachdb_db:
        name: geographic_sales
        state: present
        host: "{{ cockroach_host }}"
        port: "{{ cockroach_port }}"
        user: "{{ cockroach_user }}"
        ssl_cert: "{{ cockroach_ssl_cert }}"
        ssl_key: "{{ cockroach_ssl_key }}"
        ssl_rootcert: "{{ cockroach_ssl_rootcert }}"

    - name: Create regional_users table with LIST partitioning
      cockroachdb_table:
        name: regional_users
        database: geographic_sales
        state: present
        columns:
          - name: id
            type: UUID
            primary_key: true
            nullable: false
            default: "gen_random_uuid()"
          - name: username
            type: STRING
            nullable: false
          - name: email
            type: STRING
            nullable: false
          - name: region
            type: STRING
            nullable: false
          - name: created_at
            type: TIMESTAMP
            default: "now()"
        partition_by:
          type: LIST
          columns:
            - region
          partitions:
            - name: north_america
              values: [["US"], ["CA"], ["MX"]]
            - name: europe
              values: [["UK"], ["DE"], ["FR"], ["ES"], ["IT"]]
            - name: asia_pacific
              values: [["CN"], ["JP"], ["AU"], ["IN"]]
            - name: other_regions
              values: [["DEFAULT"]]
        host: "{{ cockroach_host }}"
        port: "{{ cockroach_port }}"
        user: "{{ cockroach_user }}"
        ssl_cert: "{{ cockroach_ssl_cert }}"
        ssl_key: "{{ cockroach_ssl_key }}"
        ssl_rootcert: "{{ cockroach_ssl_rootcert }}"
      register: partitioned_users_table

    - name: Display partitioned users table result
      ansible.builtin.debug:
        var: partitioned_users_table

    - name: Create time_series_data table with RANGE partitioning by date
      cockroachdb_table:
        name: time_series_data
        database: geographic_sales
        state: present
        columns:
          - name: id
            type: UUID
            primary_key: true
            nullable: false
            default: "gen_random_uuid()"
          - name: metric
            type: STRING
            nullable: false
          - name: timestamp
            type: TIMESTAMP
            nullable: false
          - name: value
            type: FLOAT
            nullable: false
        partition_by:
          type: RANGE
          columns:
            - timestamp
          partitions:
            - name: q1_2025
              values: [["2025-01-01"], ["2025-04-01"]]
            - name: q2_2025
              values: [["2025-04-01"], ["2025-07-01"]]
            - name: q3_2025
              values: [["2025-07-01"], ["2025-10-01"]]
            - name: q4_2025
              values: [["2025-10-01"], ["2026-01-01"]]
        host: "{{ cockroach_host }}"
        port: "{{ cockroach_port }}"
        user: "{{ cockroach_user }}"
        ssl_cert: "{{ cockroach_ssl_cert }}"
        ssl_key: "{{ cockroach_ssl_key }}"
        ssl_rootcert: "{{ cockroach_ssl_rootcert }}"
      register: time_series_table

    - name: Display time series table result
      ansible.builtin.debug:
        var: time_series_table

    - name: Create distributed_counter table with HASH partitioning
      cockroachdb_table:
        name: distributed_counter
        database: geographic_sales
        state: present
        columns:
          - name: counter_id
            type: INT
            primary_key: true
            nullable: false
          - name: counter_name
            type: STRING
            nullable: false
          - name: counter_value
            type: INT
            nullable: false
            default: "0"
        partition_by:
          type: HASH
          columns:
            - counter_id
          partitions:
            - name: part1
              values: [2]
            - name: part2
              values: [2]
        host: "{{ cockroach_host }}"
        port: "{{ cockroach_port }}"
        user: "{{ cockroach_user }}"
        ssl_cert: "{{ cockroach_ssl_cert }}"
        ssl_key: "{{ cockroach_ssl_key }}"
        ssl_rootcert: "{{ cockroach_ssl_rootcert }}"
      register: hash_partitioned_table

    - name: Display hash partitioned table result
      ansible.builtin.debug:
        var: hash_partitioned_table

    - name: Create indexes for partitioned tables
      block:
        - name: Create index on regional_users email
          cockroachdb_index:
            name: idx_regional_users_email
            database: geographic_sales
            table: regional_users
            columns:
              - email
            host: "{{ cockroach_host }}"
            port: "{{ cockroach_port }}"
            user: "{{ cockroach_user }}"
            ssl_cert: "{{ cockroach_ssl_cert }}"
            ssl_key: "{{ cockroach_ssl_key }}"
            ssl_rootcert: "{{ cockroach_ssl_rootcert }}"

        - name: Create index on time series metric
          cockroachdb_index:
            name: idx_time_series_metric
            database: geographic_sales
            table: time_series_data
            columns:
              - metric
              - timestamp
            host: "{{ cockroach_host }}"
            port: "{{ cockroach_port }}"
            user: "{{ cockroach_user }}"
            ssl_cert: "{{ cockroach_ssl_cert }}"
            ssl_key: "{{ cockroach_ssl_key }}"
            ssl_rootcert: "{{ cockroach_ssl_rootcert }}"

    - name: Get information about the partitioned tables
      cockroachdb_info:
        type: tables
        database: geographic_sales
        host: "{{ cockroach_host }}"
        port: "{{ cockroach_port }}"
        user: "{{ cockroach_user }}"
        ssl_cert: "{{ cockroach_ssl_cert }}"
        ssl_key: "{{ cockroach_ssl_key }}"
        ssl_rootcert: "{{ cockroach_ssl_rootcert }}"
      register: tables_info

    - name: Display tables information
      ansible.builtin.debug:
        var: tables_info
